/* Generated by tools/build_script.js. Change lines.json, then run it again. */
var VOICE_SCRIPT = [
 {
  "id": "narrator-01",
  "speaker": "narrator",
  "scene": "Intro",
  "text": "“Welcome to Dock Nine. Mind the gap, and mind your manners.”"
 },
 {
  "id": "narrator-02",
  "speaker": "narrator",
  "scene": "Intro",
  "text": "“Nobody has ever left Dock Nine the same way they arrived.”"
 },
 {
  "id": "captain-01",
  "speaker": "captain",
  "scene": "Bridge",
  "text": "“Hold her steady. We are not paying for another hull.”"
 },
 {
  "id": "robot-01",
  "speaker": "robot",
  "scene": "Bridge",
  "text": "PROXIMITY ALERT. SOMETHING LARGE IS APPROACHING THE DOCK.",
  "spoken": "Proximity alert. Something large is approaching the dock."
 }
];
