#!/usr/bin/env node
/* Build script.js (what the runtime and the booth load) from lines.json.

     node tools/build_script.js          write script.js
     node tools/build_script.js --check  exit 1 if script.js is out of date

   lines.json is [{ "speaker": "narrator", "scene": "Intro", "text": "..." }].
   Add "spoken" if the words to say differ from the words on screen (a label
   in front, say). Write your own extractor if your lines live in code: all it
   has to do is emit lines.json.

   IDs are pinned. A line keeps its id while its words stay the same. Change
   the words and the line gets a new id; the old one is kept as retired, so a
   take is never attached to words it wasn't recorded on. To keep an id across
   a rewording on purpose (an actor changed a line in the booth and you took
   it), list it in reworded.json: [{ "id": "narrator-01", "text": "new words" }]. */
const fs = require("fs");
const path = require("path");
const root = path.join(__dirname, "..");
const read = (f) => fs.readFileSync(path.join(root, f), "utf8");

function build(lines, old, reworded) {
  const byText = new Map(old.filter((o) => !o.retired).map((o) => [o.text, o]));
  for (const r of reworded) byText.set(r.text, { id: r.id });
  const used = new Set(old.map((o) => o.id)), counter = {};
  for (const o of old) { const m = /^(.+)-(\d+)$/.exec(o.id); if (m) counter[m[1]] = Math.max(counter[m[1]] || 0, +m[2]); }
  const seen = new Set(), script = [];
  for (const l of lines) {
    if (seen.has(l.text)) continue;               // the same words said again are one line
    seen.add(l.text);
    let id = byText.get(l.text) && byText.get(l.text).id;
    if (!id) {
      do { counter[l.speaker] = (counter[l.speaker] || 0) + 1; id = l.speaker + "-" + String(counter[l.speaker]).padStart(2, "0"); } while (used.has(id));
      used.add(id);
    }
    const out = { id, speaker: l.speaker, scene: l.scene || "", text: l.text };
    if (l.spoken) out.spoken = l.spoken;
    script.push(out);
  }
  const retired = old.filter((o) => !script.some((s) => s.id === o.id)).map((o) => ({ ...o, retired: true }));
  return script.concat(retired);
}

const render = (script) => "/* Generated by tools/build_script.js. Change lines.json, then run it again. */\nvar VOICE_SCRIPT = " + JSON.stringify(script, null, 1) + ";\n";
const parse = (src) => JSON.parse(src.slice(src.indexOf("=") + 1).replace(/;\s*$/, ""));

if (require.main === module) {
  const opt = (f, d) => { try { return JSON.parse(read(f)); } catch (e) { return d; } };
  let old = []; try { old = parse(read("script.js")); } catch (e) { /* first run */ }
  const js = render(build(opt("lines.json", []), old, opt("reworded.json", [])));
  if (process.argv.includes("--check")) {
    let cur = ""; try { cur = read("script.js"); } catch (e) { /* missing */ }
    if (cur !== js) { console.error("script.js is out of date. Run: node tools/build_script.js"); process.exit(1); }
    console.log("script.js is current");
  } else {
    fs.writeFileSync(path.join(root, "script.js"), js);
    console.log("wrote script.js: " + parse(js).filter((s) => !s.retired).length + " lines");
  }
}
module.exports = { build, render, parse };
